version: '3'

vars:
  BIN_DIR: "./bin"
  SERVER_EXE: "nyx-server"

tasks:
  init:
    desc: "Create binaries directory"
    cmds:
      - mkdir -p {{.BIN_DIR}}

  build-server:
    dir: ./backend
    desc: "Build web server interface"
    deps: [init]
    cmds:
      - go build -o ../{{.BIN_DIR}}/{{.SERVER_EXE}} ./cmd/api

  all:
    desc: "Build both interfaces"
    cmds:
      - task: build-server

  clean:
    desc: "Remove all build artifacts"
    cmds:
      - rm -rf {{.BIN_DIR}}/*
      - go clean

  run-server:
    desc: "Build and run web server"
    cmds:
      - task: build-server
      - "{{.BIN_DIR}}/{{.SERVER_EXE}}"